### ISSUE TITLE
2019年版のページを作成する.

### ISSUE THREAD

**Issue by OhataKenji** [IGGG/guntoh-fes#2]
2019年度版のページを作成したい.

https://iggg.github.io/guntoh-fes/2019

とかで行けるようにしたい.

**Comment by OhataKenji** [comment]
https://iggg.github.io/guntoh-fes/
で2017
https://iggg.github.io/guntoh-fes/2016
で2016

でるのは不自然なので直したい?

**Comment by matsubara0507** [comment]
前は2017版作った時に2016版を `/2016` に移した（ような気がする

**Comment by matsubara0507** [comment]
理想は
- `https://iggg.github.io/guntoh-fes/xxxx` で xxxx 年のが見れる
- `https://iggg.github.io/guntoh-fes` で最新のが見れる

だけど `https://iggg.github.io/guntoh-fes/2017` をサボったアルネ

**Comment by OhataKenji** [comment]
```2017```を移して
```index.html```は```2019/front```を参照するようにすれば良さそうですね

**Comment by matsubara0507** [comment]
アプリ提出

- 名前: AnaQRam
- 画像: 以下

![image](https://user-images.githubusercontent.com/10684493/66571920-1376d280-ebab-11e9-8063-f3ac27ffa790.png)

動きある動きあるやつ撮るのめんどいな
あ、これちょっと古いな。まぁいいか。

**Comment by OhataKenji** [comment]
create2019pageで2019年のページを作ったほうがいいのか
新しいブランチ立てるべきかどっちなんでしょうか?

**Comment by matsubara0507** [comment]
どっちでもいいよ 👍

**Comment by OhataKenji** [comment]
群桐祭無事終了!!
