### ISSUE TITLE
フロントページが何もない

### ISSUE THREAD

**Issue by matsubara0507** [IGGG/guntoh-fes#5]
https://iggg.github.io/guntoh-fes/

見れないね

**Comment by atpons** [comment]
心がきれいな人にしか見えないやつ

**Comment by atpons** [comment]
ワイは見えなかったのでだめです...............................

**Comment by OhataKenji** [comment]
見える!!

**Comment by OhataKenji** [comment]
![Screenshot from 2019-10-12 14-47-18](https://user-images.githubusercontent.com/11045367/66695652-492cd000-ecff-11e9-9442-3c54dd45716e.png)

index.html入れればいいのか
